# Generated by Django 5.2.3 on 2025-07-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasl',
            new_name='Task',
        ),
    ]
